### ISSUE TITLE
Localhost only?

### ISSUE THREAD

**Issue by XanderStrike** [digidigital/quakejs-installer#3]
I'm trying to build and install this in a Ubuntu based Docker container on a remote machine, and I've replaced `127.0.0.1` in `startscript.sh` to the public IP:PORT of my server, but when loading the page I still see a failed request to `http://127.0.0.1/assets/manifest.json`. I've verified that `http://<server port:ip>/assets/manifest.json` works and contains what I expect.

I've searched the contents of quakejs and I don't really see where this ip is hardcoded, hoping you might know why it's trying to call localhost

**Comment by digidigital** [comment]
If you have executed the installer without setting the IP and port in installerconfig.cfg to something different than 127.0.0.1 and 27960 the index.html contains the link to 127.0.0.1 and you have to manually set the right values.

Open /var/www/html/index.html and search for the line containing "var args =" and check if it contains the correct values.
